export enum Commands {
  InitStandaloneListBox = "init_standalone_listbox",
  InitRecordingInputOptions = "init_recording_input_options",
  CheckPermissions = "check_permissions",
  RequestPermission = "request_permission",
  OpenSystemSettings = "open_system_settings",
  QuitApp = "quit_app",
  ShowStandaloneListBox = "show_standalone_listbox",
  HideStartRecordingDock = "hide_start_recording_dock",
  ShowRecordingInputOptions = "show_recording_input_options",
  StartAudioListener = "start_audio_listener",
  StopAudioListener = "stop_audio_listener",
  ListAudioInputs = "list_audio_inputs",
  IsStartRecordingDockOpen = "is_start_recording_dock_open",
  IsRecordingInputOptionsOpen = "is_recording_input_options_open",
  ListCameras = "list_cameras",
  StartCameraStream = "start_camera_stream",
  StopCameraStream = "stop_camera_stream",
}
