export enum Events {
  MonitorPermissions = "monitor_permissions",
  ClosedStandaloneListBox = "closed_standalone_listbox",
  StartRecordingDockOpened = "start_recording_dock_opened",
  RecordingInputOptionsOpened = "recording_input_options_opened",
  RecordingStarted = "recording_started",
  ClosedRecordingInputOptions = "closed_recording_input_options",
  SystemAudioStreamError = "system_audio_stream_error",
  MicrophoneStreamError = "microphone_stream_error",
  CollapsedRecordingSourceSelector = "collapsed_recording_source_selector",
  WindowThumbnailsGenerated = "window_thumbnails_generated",
  RecordingComplete = "recording_complete",
  ClosedEditor = "closed_editor",
  ExportProgress = "export_progress",
  ExportComplete = "export_complete",
}
