name: Sanity Check

on:
  pull_request:
    branches: [main]

jobs:
  sanity-check:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Read Node.js from .nvmrc
        id: nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features sqlite

      - name: Create SQLite database
        working-directory: src-tauri
        env:
          DATABASE_URL: sqlite:${{ runner.temp }}/sanity.db
        run: |
          echo "DATABASE_URL=$DATABASE_URL"
          sqlx database create
          sqlx migrate run

      - name: Write .env with DATABASE_PATH for build scripts
        working-directory: src-tauri
        run: echo "DATABASE_PATH=\"${{ runner.temp }}/sanity.db\"" > .env && cat .env

      - name: clippy
        working-directory: src-tauri
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Cargo fmt check
        working-directory: src-tauri
        run: cargo fmt --all -- --check
